services:
  db:
    image: postgres:14-alpine
    container_name: pg-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/docker/initdb:/docker-entrypoint-initdb.d
volumes:
  postgres-data: